@startuml
' + - public
' # - protected
' - - private 
' ~ - package private

''' GameController '''
class GameController {
    IsMenuActive : bool
    RunCommand(string input) : void
    GameFactory(GameConfig config) : Game
    void Start() :
    void NewGame()
    void LoadGame()
}

''' Game '''
abstract class Game {
    Grid : Grid
    PlayerOne : Player
    PlayerTwo: Player
    IsGameActive : bool
    AllowedDiscChars : char[]
    MoveSequence : list<Move>
    FileController : file
    IComputerStrategy : computerStrategy

    GetInputGame() : string
    void DocumentMove(string move)
    void UndoMove()
    RedoMove() : bool
    PlayMoveSequence(int moveCount) : bool
    TryHandleCommand(string input) : bool
    TryParseMove(string input, out int lane) : bool
    PlayTurn(Human player) : bool
    PlayTurn(Computer player) : bool
    void TestLoop()
    {abstract} void CheckBoard()
    {abstract} CreateDisc() : Disc
    void GameLoop()
    void Reset()
    {virtual} void PrintPlayerData()
}

' Game Subclasses
class LineUpClassic {
    LineUpClassic()
    override void CheckBoard()
}

class LineUpBasic {
    LineUpBasic()
    override void CheckBoard()
}

class LineUpSpin {
    LineUpSpin()
    override void CheckBoard()
}

''' Grid '''
class Grid {
    Board : Disc[][]
    Orientation : enum
    orientation : Orientation
    WinLength : int
    TurnCounter : int
    void IncrementTurnCounter()
    void DecrementTurnCounter()
    SetTurnCounter(int num) : bool
    void IncrementOrientation()
    IsTieGame(Player p1, Player p2) : bool
    AddDisc(Move move) : bool
    void ApplyGravity()
    void Spin()
    void DrawGrid()
    CheckWinCondition() : bool
    void Reset()
}

enum Orientation {
    North
    East
    South
    West
}

'''Disc'''
abstract class Disc {
    Symbol : string
    IsPlayerOne : bool
    DiscReturn : Dictionary<string, int>[]
    CreateDisc(char discType, bool isPlayerOne) : static
    {abstract} Clone() : Disc
    {abstract} ApplyEffects(Disc[][] Board, int lane) : bool
    {abstract} HasDiscRemaining(Player player) : bool
    {abstract} void WithdrawDisc(Player player)
}

class OrdinaryDisc {
    OrdinaryDisc
    override ApplyEffects(Disc[][] Board, int lane) : bool
    override Clone() : Disc
    HasDiscRemaining(Player player) : bool
    WithdrawDisc(Player player) : void
}

class BoringDisc {
    BoringDisc
    override ApplyEffects(Disc[][] Board, int lane) : bool
    override Clone() : Disc
    HasDiscRemaining(Player player) : bool
    WithdrawDisc(Player player) : void
}

class Exploding {
    ExplodingDisc
    override ApplyEffects(Disc[][] Board, int lane) : bool
    override Clone() : Disc
    HasDiscRemaining(Player player) : bool
    WithdrawDisc(Player player) : void
}

class MagneticDisc {
    MagneticDisc
    override ApplyEffects(Disc[][] Board, int lane) : bool
    override Clone() : Disc
    HasDiscRemaining(Player player) : bool
    WithdrawDisc(Player player) : void
}

class Move {
    Disc : Disc 
    Lane : int
    Move(Disc disc, int lane)
}

''' Player ''' 
class Player {
    DiscBalance : Dictionary<string, int>
    IsHuman : bool
    Player(Dictionary<string, int> discBalance, bool isHuman = true)
    HasDiscBalanceRemaining() : bool
    void ResetDiscBalance(Dictionary<string, int> DiscBalance_)
    void ReturnDisc(Dictionary<string, int> discReturned)
}

interface IComputerStrategy {
    Move SelectMove(Grid grid, Player player)
}

class BasicComputerStrategy {
    Random : random;
    BasicComputerStrategy()
    SelectMove(Grid grid, Player player): Move
    FindWinningMove(Grid grid, Player player) : Move
    FindRandomMove(Grid grid, Player player) : Move
    TrySimulateMove() : bool
    CopyGrid() : Grid
}

''' IOController '''
class IOController {
    static void PrintGreen(string text)
    static void PrintCyan(string text)
    static void PrintYellow(string text)
    static void PrintError(string text)
    static void PrintSuccess(string text)
    static void PrintMenu()
    static void PrintBannerNewGame()
    static void PrintHelp()
    static void PrintInGameHelp()
    static void PrintSaveFiles()
    static void PrintWinner(bool P1, bool P2)
    static GetInputMenu() : int
    static GetInputLoad() : string
    static GetInputNewGame() : GameConfig
}

note left of IOController::GetInputNewGame
    Currently responsible for too much.
    Will need to be broken into:
    GetInputGameMode
    GetInputPlayerMode
    GetInputGridSize
end note


''' GameConfig '''
class GameConfig {
    PlayerMode : enum
    GameMode : enum
    SelectedPlayerMode : PlayerMode
    SelectedGameMode : GameMode
    GridHeight : int
    GridWidth : int
    GameConfig()
    SetGameMode(GameMode mode) : bool
    SetPlayerMode(PlayerMode mode) : bool
    SetGridHeight(int rows) : bool
    SetGridWidth(int cols) : bool
}

enum PlayerMode {
    HvH
    HvC
}

enum GameMode {
    Classic
    Basic
    Spin
}

''' FileController '''
class FileController {
    void GameSerialization()
    GetSaves() : string
    GameDeserialization() : Game
}

' Relationships
' Game Subclasses
Game <|-- LineUpClassic : inherits
Game <|-- LineUpBasic : inherits
Game <|-- LineUpSpin : inherits
Game <-- Player

Game::Grid *-- "1" Grid : uses
Game - IOController

' GameController
GameController - Game
GameController <-- IOController
GameController::LoadGame <-- FileController : uses

' GameConfig
GameConfig::PlayerMode <-- PlayerMode : uses
GameConfig::GameMode <-- GameMode: uses

' Player
BasicComputerStrategy <|.. IComputerStrategy
BasicComputerStrategy <-- Move : uses

' Disc Subclasses
Disc <|-- OrdinaryDisc : inherits
Disc <|-- BoringDisc : inherits
Disc <|-- ExplosiveDisc : inherits
Disc <|-- MagneticDisc : inherits

' Grid
Grid::Orientation <-- Orientation : uses
Grid::Board <-- Disc : uses
Grid::Move <-- Move : uses

' Move

Move::Disc <-- Disc : uses

' IOController
IOController <-- GameConfig

@enduml