@startuml
skinparam actorStyle awesome
skinparam titleFontSize 32
title Sequence Diagram – LineUpClassic Game (Human vs Computer Mode)

actor User as "Human Player"
participant GameController
participant IOController
participant GameConfig
participant LineUpClassic as Game
participant Grid
participant Human
participant Disc
participant Computer as IComputerStrategy

== Game Initialisation ==

User -> GameController: NewGame()
activate GameController
loop While IsMenuActive == true
    activate IOController
    GameController -> IOController: PrintMenu()
    IOController -> User: Display game mode options
    User -> IOController: Select "LineUpClassic"
    IOController -> GameConfig: GameMode "Classic"
    IOController -> User: Display player mode options
    User -> IOController: Select "HvC"
    IOController -> GameConfig: PlayerMode "HvC"
    IOController -> User: Change Grid size?
    User -> IOController: Select "No"
    IOController -> GameConfig: GetInputNewGame()
    deactivate IOController
    GameController -> GameConfig: GameFactory()
    GameConfig -> GameController: GameFactory(config)

    == Start Game Loop ==
    activate Game
    GameController -> Game: GameLoop()
    deactivate GameController

    loop While IsGameActive == true
    Game -> User: PrintPlayerData()
    Game -> User: DrawGrid()
    alt Human Player Turn
        Game -> Game: PlayerTurn(PlayerOne)
        activate Game
        deactivate Game
        Game -> User: GetInputGame()
        alt Make move
            User -> Game: Enter move
            Game -> Disc: CreateDisc()
            activate Disc
            Game -> Disc: HasDiscRemaining() == true
            Disc -> Game: disc
            activate Grid
            Game -> Grid: AddDisc(disc, lane)
            deactivate Grid
            Game -> Disc: ApplyEffects(Board, lane)
            opt EffectTriggered
                activate Grid
                Disc -> Grid: ApplyGravity()
            end
                deactivate Disc
            Game -> Grid: DrawGrid()
            alt Is Tie Game
                Grid -> Grid: IsTieGame(PlayerOne, PlayerTwo)
                activate Grid
                deactivate Grid
                Grid -> Game: IsTieGame = true
                Game -> IOController: PrintWinner(P1)
                Game -> Game: IsGameActive = false
                activate Game
                deactivate Game
            else Winner Found
                Game -> Grid: CheckWinCondition()
                Grid -> Game: CheckWinCondition(P1) = true
                Game -> IOController: PrintWinner(P1)
                Game -> Game: IsGameActive = false
                activate Game
                deactivate Game
            else Continue Game
                Game -> Grid: CheckWinCondition()
                Grid -> Game: CheckWinCondition = false
                Game -> Grid: IncrementTurnCounter()
            deactivate Grid
            end
            Game -> Game: DocumentMove(move)
            activate Game
            deactivate Game
        else Help/Undo/Redo/Quit command
            Game -> Game: TryHandleCommand()
            activate Game
            deactivate Game
        end
    else Computer Player Turn
        Game -> Game: PlayerTurn(PlayerTwo)
        activate Game
        deactivate Game
        activate IComputerStrategy
        Game -> IComputerStrategy: SelectMove()
        IComputerStrategy --> Game: Move{Disc, Lane}
        deactivate IComputerStrategy
        activate Disc
        Game -> Disc: CreateDisc()
        Disc -> Game: disc
        activate Grid
        Game -> Grid: AddDisc(disc, lane)
        Game -> Disc: ApplyEffects(Board, lane)
        opt EffectTriggered
            Disc -> Grid: ApplyGravity()
        end
        deactivate Disc
        alt Is Tie Game
            Grid -> Grid: IsTieGame(PlayerOne, PlayerTwo)
            activate Grid
            deactivate Grid
            Grid -> Game: IsTieGame = true
            Game -> IOController: PrintWinner(P2)
            Game -> Game: IsGameActive = false
            activate Game
            deactivate Game
        else Winner Found
            Game -> Grid: CheckWinCondition()
            Grid -> Game: CheckWinCondition(P2) = true
            Grid -> IOController: PrintWinner(P2)
            Game -> Game: IsGameActive = false
            activate Game
            deactivate Game
        else Continue Game
            Game -> Grid: CheckWinCondition()
            Grid -> Game: CheckWinCondition = false
            Game -> Grid: IncrementTurnCounter()
        deactivate Grid
        end
        Game -> Game: DocumentMove(move)
        activate Game
        deactivate Game
    end
deactivate Game
end

== Game Over ==
