@startuml
skinparam actorStyle awesome
title Sequence Diagram – LineUpClassic Game (Human vs Computer Mode)

actor User as "Human Player"
participant GameController
participant IOController
participant GameConfig
participant LineUpClassic as Game
participant Grid
participant Human
participant Disc
participant Computer
participant IComputerStrategy as "AI Strategy"
participant FileController

== Game Initialisation ==

User -> GameController: NewGame()
activate GameController
loop While IsMenuActive == true
    activate IOController
    GameController -> IOController: PrintMenu()
    IOController -> User: Display game mode options
    User -> IOController: Select "LineUpClassic"
    IOController -> GameConfig: GameMode "Classic"
    IOController -> User: Display player mode options
    User -> IOController: Select "HvC"
    IOController -> GameConfig: PlayerMode "HvC"
    IOController -> User: Change Grid size?
    User -> IOController: Select "No"
    IOController -> GameConfig: GetInputNewGame()
    deactivate IOController
    GameConfig -> GameController: GameFactory()
    deactivate GameController

    == Start Game Loop ==
    activate Game
    GameController -> Game: GameLoop()

    loop While IsGameActive == true
    Game -> User: PrintPlayerData()
    Game -> User: DrawGrid()
    alt Human Player Turn
        Game -> User: GetInputGame()
        User -> Game: Enter move/command
        Game -> Game: PlayerTurn(PlayerOne)
        alt Make move
            activate Disc
            Game -> Disc: CreateDisc()
            Game -> Disc: HasDiscRemaining() == true
            Disc -> Game: disc
            activate Grid
            Game -> Grid: AddDisc(disc, lane)
            deactivate Grid
            Game -> Disc: ApplyEffects(Board, lane)
            alt EffectTriggered
                activate Grid
                Disc -> Grid: ApplyGravity()
            end
                deactivate Disc
            Game -> Grid: DrawGrid()
            alt Is Tie Game
                Grid -> Grid: IsTieGame(PlayerOne, PlayerTwo)
                Grid -> Game: IsTieGame = true
            else Winner Found
                Game -> Grid: CheckWinCondition()
                Grid -> Game: CheckWinCondition(P1) = true
            else Continue Game
                Game -> Grid: CheckWinCondition()
                Grid -> Game: CheckWinCondition = false
                Game -> Grid: IncrementTurnCounter()
            deactivate Grid
            end
            Game -> Game: DocumentMove(move)            
        else Help/Undo/Redo/Quit command
            Game -> Game: Help/Redo/Undo/Quit
        end
    else Computer Player Turn
        activate IComputerStrategy
        Game -> IComputerStrategy: SelectMove()
        IComputerStrategy --> Game: Move{Disc, Lane}
        deactivate IComputerStrategy
        activate Disc
        Game -> Disc: CreateDisc()
        Disc -> Game: disc
        activate Grid
        Game -> Grid: AddDisc(disc, lane)
        Game -> Disc: ApplyEffects(Board, lane)
        alt EffectTriggered
            activate Grid
            Disc -> Grid: ApplyGravity()
        end
        deactivate Disc
        alt Is Tie Game
            Grid -> Grid: IsTieGame(PlayerOne, PlayerTwo)
            Grid -> Game: IsTieGame = true
        else Winner Found
            Game -> Grid: CheckWinCondition()
            Grid -> Game: CheckWinCondition(P2) = true
        else Continue Game
            Game -> Grid: CheckWinCondition()
            Grid -> Game: CheckWinCondition = false
            Game -> Grid: IncrementTurnCounter()
        deactivate Grid
        end
        Game -> Game: DocumentMove(move)
    end

    alt Winner Found
        Grid -> IOController: PrintWinner(P1 | P2)
        Game -> Game: IsGameActive = false
    else Tie Game
        Game -> IOController: PrintWinner(P1 && P2)
        Game -> Game: IsGameActive = false
    end
end

== Game Over ==
